name: Unpublish expired events

on:
  repository_dispatch:
    types:
      - resource-published

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd ${RUNNER_WORKSPACE} && find .
    # - run: find .
    - run: env | sort
    - run: pwd
    - run: node .github/workflows/node/schedule-unpublish.js one two three